In [9]:
import numpy as np

# Define matrix A
A = np.array([[3,1,1],[-1,3,1]])

# Perform SVD
U, s, Vt = np.linalg.svd(A)

# Recombine matrices
sigma = np.zeros((A.shape[0], A.shape[1]))
sigma[:A.shape[1], :A.shape[0]] = np.diag(s)

B = U.dot(sigma.dot(Vt))

# Print matrices and vectors
print("A:\n", A)
print("U:\n", U)
print("sigma:\n", sigma)
print("Vt:\n", Vt)
print("B:\n", B)

# Transform A into Ὰ by selecting the first two features
A_t = U[:, :2].dot(sigma[:2, :2].dot(Vt[:2, :]))

# Print transformed matrix
print("A_t:\n", A_t)


A:
 [[ 3  1  1]
 [-1  3  1]]
U:
 [[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]
sigma:
 [[3.46410162 0.         0.        ]
 [0.         3.16227766 0.        ]]
Vt:
 [[-4.08248290e-01 -8.16496581e-01 -4.08248290e-01]
 [-8.94427191e-01  4.47213595e-01  5.26260748e-16]
 [-1.82574186e-01 -3.65148372e-01  9.12870929e-01]]
B:
 [[ 3.  1.  1.]
 [-1.  3.  1.]]
A_t:
 [[ 3.  1.  1.]
 [-1.  3.  1.]]
